Cs 229 design many to many
csatar/csatar-october pull request #102
Opened 2022-07-21 22:50 UTC by atla333

- Changed grid solution using cards
- Deleted earlier grid solution from design system
- Fixed cards bottom rounded corner
- Fixed Form field height (added min-height)

2022-07-22 08:54 UTC, zsso commented on csatar-theme/assets/css/csatar-custom-styles.css
> +.label {
Itt a .label és .data túl általános, kellene valami prefix vagy, hogy csak akkor működijön ha egy bizonyos szülő elemben van benne, pl. 'csat-resp-gdtable'. Mert így könnyen lehet, hogy valahol máshol az oldalon lesz még .label vagy .data osztállyal más elem amit elront.

2022-07-22 09:03 UTC, zsso requested changes

2022-07-22 17:15 UTC, atla333 commented on csatar-theme/assets/css/csatar-custom-styles.css
> +.label {
Javítva!

2022-07-25 14:56 UTC, zsso approved these changes

2022-07-25 16:23 UTC, merged